# Generated by Django 5.2.14 on 2026-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaagRoom',
            fields=[
                ('room_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('laag_date', models.CharField(blank=True, default='Saturday', max_length=255)),
                ('participants', models.CharField(blank=True, default='murag 5 persons haha', max_length=255)),
                ('service', models.CharField(blank=True, default='3 motors', max_length=255)),
                ('meetup_area', models.CharField(blank=True, default='TBA HAHA', max_length=255)),
                ('meetup_time', models.CharField(blank=True, default='8:00 AM – Meet up daw forsure 9 nasad ka abot haha', max_length=255)),
                ('food_items', models.JSONField(blank=True, default=list)),
                ('foods', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'laag_rooms',
            },
        ),
    ]
