# Generated by Django 5.2.14 on 2026-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laagroom',
            name='active_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
